version: '3.8'

services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - 3306:3306
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - ./data/mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
